# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=140)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_user', models.CharField(choices=[('Maestro', 'Maestro'), ('Alumno', 'Alumno')], default='Alumno', max_length=140)),
            ],
        ),
    ]
