# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_perfil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='apellidoM',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellidoP',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
